BASE_ACTION_VOILES = 10
BASE_ACTION_FLECHES = 10
BASE_ACTION_RAMES = 10
BASE_ACTION_SOINS = 10

BASE_SPEED = 50

BASE_REPARE_COQUE = 0
BASE_REPARE_RAMES = 0
BASE_REPARE_VOILES = 0

BASE_DAMAGE_ARROW = 10
BASE_DAMAGE_ARROW_FIRE = 2
BASE_DAMAGE_BRISE_COQUE = 50

LONGUEUR_NAVIRE = 4*16
LARGEUR_NAVIRE = 2*16

INERTIE = 10