BASE_POS_NAVIRE1 = [128, 20]
BASE_POS_NAVIRE2 = [128, 120]

BASE_ACTION_LIBRE = 10
BASE_ACTION_FLECHES = 30
BASE_ACTION_RAMES = 40
BASE_ACTION_SOINS = 20

BASE_SPEED = 50

BASE_REPARE_COQUE = 0
BASE_REPARE_RAMES = 0
BASE_REPARE_VOILES = 0

BASE_DAMAGE_ARROW = 10
BASE_DAMAGE_ARROW_FIRE = 2
BASE_DAMAGE_BRISE_COQUE = 20

LONGUEUR_NAVIRE = 88
LARGEUR_NAVIRE = 48

INERTIE = 10